[programs.devnet]
buildspacesolprogram = "2KUJfwMchPJYaT2yPrDmETtq1d77rPHsEX3rb7Je3DS9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/masangri/.config/solana/id.json"

[scripts]
test = "node tests/buildspacesolprogram.ts"
